# TEMPLATE FOR LOCAL USAGE ONLY

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus - statement-downloader

Globals:
  Function:
    Environment:
      Variables:
        DISABLE_SIGNAL_HANDLERS: true

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api-authorizer/target/function.zip
      Handler: com.ebanx.lambda.ApiAuthorizerHandler::handleRequest
      Runtime: java11

  ApiAuthorizerGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt AuthFunction.Arn

  StatementDownloaderLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'statement-downloader'
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      CodeUri: downloader/target/function.zip
      MemorySize: 512
      Timeout: 900
      Events:
        ApiResource:
          Type: Api
          Properties:
            Path: "/statement/v1/download"
            Method: "GET"
            RestApiId: !Ref ApiAuthorizerGateway