# TEMPLATE FOR LOCAL USAGE ONLY

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus - statement-downloader

Globals:
  Function:
    Environment:
      Variables:
        DISABLE_SIGNAL_HANDLERS: true
        BUCKET: !Ref AccountStatementBucketName

Parameters:
  AccountStatementBucketName:
    Type: String
    Default: "account-statement-bucket-test"
    Description: "Bucket that stores account statements in csv format"

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'statement-downloader-auth'
      CodeUri: api-authorizer/target/function.zip
      Handler: not.used.in.provided.runtime
      Runtime: provided

  ApiAuthorizerGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt AuthFunction.Arn

  StatementDownloaderLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'statement-downloader'
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: downloader/target/function.zip
      MemorySize: 512
      Timeout: 900
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AccountStatementBucketName
      Events:
        ApiResource:
          Type: Api
          Properties:
            Path: "/statement/v1/download"
            Method: "GET"
            RestApiId: !Ref ApiAuthorizerGateway